### ISSUE TITLE
JSDoc no longer highlighted on GitHub

### ISSUE THREAD

**Issue by Alhadis** [github/semantic#441] opened 2020-01-26 04:12 UTC
Recently, I noticed that [JSDoc](https://jsdoc.app/) blocks no longer receive highlighting on GitHub. [For example](https://github.com/Alhadis/Utils/blob/2cc30027c307efd9793dee52ab6504e8afe29043/lib/dom.mjs#L1-L30):

![figure-1](https://user-images.githubusercontent.com/2346707/73130529-dfd29200-404d-11ea-9a22-546a787d6240.png)

I strongly suspect this has something to do with this library, because JSDoc tags *are* highlighted correctly on [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.js&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FAlhadis%2FUtils%2Fblob%2F6769413067b9ace34c09d4cd6e6ea278078074cf%2Flib%2Fdom.mjs&code=) and in Markdown code-blocks:

~~~js
/**
 * Curried method to append multiple nodes at once.
 *
 * @example addTo(node)(el1, el2, …)
 * @example node = addTo(node)(…)[0]
 * @param {Node} parent
 * @return {Function}
 */
export function addTo(parent){
…
~~~

In addition, the `(node)(el1, el2, …)` part of the `@example` tag shouldn't be highlighted as a comment, although that might be a different issue more relevant to [Primer](https://github.com/primer).

**Comment by patrickt** [comment] 2020-01-26 23:15
Hi there! Thanks for pointing this out. While `semantic` is peripherally involved in this pipeline, the more appropriate place for this issue is in the tree-sitter-javascript repo, as the first steps to restore this functionality would have to be embedded there. I’ve taken the liberty of moving it: https://github.com/tree-sitter/tree-sitter-javascript/issues/126

**Closed by patrickt** 2020-01-26 23:15 UTC

**Comment by maxbrunsfeld** [comment] 2020-01-27 21:34
Thanks for pointing this out @Alhadis. I've pushed an update that includes [`tree-sitter-jsdoc`](https://github.com/tree-sitter/tree-sitter-jsdoc) into our backend highlighting system.

Example: https://github.com/lodash/lodash/blob/master/debounce.js

The highlighting configuration is more minimal than what the TextMate grammar did - it doesn't try to highlight the contents of `@example` blocks as JavaScript. But that feature didn't work very well with the TextMate engine either - example blocks would end up highlighted as a *mixture* of comments and highlighted content, which looked a bit odd. I think for now, I'd rather be conservative with the JSDoc highlighting, since the GitHub color palette is fairly minimal anyway.

We recently rolled out this new highlighting for several languages, and we're still in the process of documenting it. Let me know if you notice other regressions with JavaScript, TypeScript, Ruby, Python, Go, or PHP highlighting. Thanks!

**Comment by Alhadis** [comment] 2020-01-28 00:19
> example blocks would end up highlighted as a *mixture* of comments and highlighted content, which looked a bit odd

Correction: the `meta.example.jsdoc` scope wasn't resetting the base text-colour, causing unhighlighted `source.js` tokens to inherit the colour of their parent `comment.block.documentation.js` token. It's a simple styling issue that has nothing to do with the TextMate grammar itself.

Anyway, this is one of the main reasons I disabled TreeSitter in Atom in the first place: lossy and incomplete scoping (not to mention it's just a horribly everted system in general, IMHO).
